Feature/areaRepo
Dev-Osmium/text-adventure-engine pull request #16
Opened 2019-10-13 03:17 UTC by JessieVela

I know we talked about possibly not using an AreaRepo, so take a look and see if it will work. In the world.java I added an example of its use.

2019-10-13 15:13 UTC, JessieVela commented
Resolves #4

2019-10-14 21:55 UTC, JessieVela commented
Just realized I made a pull request to master; Changed to develop and fixed a merge conflict.

2019-10-15 11:53 UTC, Dev-Osmium commented
I'm a bit worried about the added complexity. Maybe we should make Areas a possible way of organizing? What do you think?

2019-10-15 14:39 UTC, JessieVela commented
It does add another layer of complexity. The benefit is you can now add locations to areas and when displaying the possible locations to a user; you can find the locations grouped together for easier processing.
Example: 
` areas.addAreaObject(new Area("Castle Throne", 1));` 
`locations.buildLocation(coord1, "Room 2", "Cafeteria where everyone eats",
                areas.searchAreaByName("Castle"));`

You created the area "Castle Throne" with a unique ID of 1 and all locations will inserted into "Castle Throne". Now when I display the possible locations I can just find the area and iterate through the locations.

2019-10-15 14:41 UTC, Dev-Osmium commented
Yeah, that makes sense. How about making them an optional part of making locations? I can think of a few scenarios where Areas don't make sense (single-area short games, single-room world sections, etc.)

2019-10-15 14:49 UTC, JessieVela commented
True. If you feel more comfortable shelving it for now i'm all game for that. It does add a layer of complexity and we could revisit it if we start to find a need for.

2019-10-15 15:01 UTC, Dev-Osmium commented
I think we just need to make it optional, add a constructor option without an Area argument.

2019-10-15 15:16 UTC, JessieVela commented
Sounds good. I'll make the changes for it to be optional.

2019-10-15 16:12 UTC, Muirrum requested changes
Overall looks good. Just do the thing I talked about upthread, and I don't know if the .idea/ folder needs to stay in, but I'll trust your judgment on that. I made a few comments as well, just change those and it should be good!

2019-10-15 16:12 UTC, Dev-Osmium commented on src/main/java/xyz/devosmium/games/textadventureengine/locations/AreaCollection.java
> +//Area Collection class will hold Areas in an ArrayList. Its primary function is to store and retrieve areas.
Can this be a javadoc comment?

2019-10-15 16:12 UTC, Dev-Osmium commented on src/main/java/xyz/devosmium/games/textadventureengine/locations/AreaCollection.java
> +}
The rest of these methods all need javadocs

2019-10-15 16:12 UTC, Dev-Osmium commented on src/main/java/xyz/devosmium/games/textadventureengine/menus/MainMenu.java
> +    World world = new World();
I think this should be put into the Game constructor, since that's where it first needs to be used.

2019-10-15 16:12 UTC, Dev-Osmium commented on src/test/java/xyz/devosmium/games/locations/AreaCollectionTest.java
> +        //Create a
Just looks a little short :D

2019-10-15 17:12 UTC, JessieVela commented on src/main/java/xyz/devosmium/games/textadventureengine/locations/AreaCollection.java
> +//Area Collection class will hold Areas in an ArrayList. Its primary function is to store and retrieve areas.
Definitely, I will change it.

2019-10-15 17:14 UTC, JessieVela commented on src/main/java/xyz/devosmium/games/textadventureengine/locations/AreaCollection.java
> +}
Will add proper javadoc to these methods.

2019-10-15 17:15 UTC, JessieVela commented on src/test/java/xyz/devosmium/games/locations/AreaCollectionTest.java
> +        //Create a
Fixing it. How that happen xD

2019-10-15 17:17 UTC, JessieVela commented on src/main/java/xyz/devosmium/games/textadventureengine/menus/MainMenu.java
> +    World world = new World();
Agreed. Moving it into the Game constructor.

2019-10-16 03:13 UTC, JessieVela commented
Fixed the changes.

2019-10-16 17:17 UTC, Muirrum requested changes
App.java throws an error (https://scans.gradle.com/s/tgstkxv72ehsm). Looks like you forgot an import in it.

2019-10-17 02:36 UTC, JessieVela commented
Fixed the error. It was a good catch my local machine ran without throwing the error.

2019-10-17 14:51 UTC, Muirrum approved these changes
Looks good to me!

2019-10-17 14:51 UTC, merged