Feature/save manager
Dev-Osmium/text-adventure-engine pull request #20
Opened 2019-10-23 16:27 UTC by JessieVela

Created a base save provider where it gives the option to save in SQLite database. Currently, Player is implemented and created so it is able to be saved to the database. Removed the .idea folder from the project.

2019-10-24 12:02 UTC, Muirrum requested changes
Saving here looks good, but it needs to include loading.

2019-10-24 12:02 UTC, Muirrum commented on src/main/java/xyz/devosmium/games/textadventureengine/mobiles/Mobile.java
> +    private String playerID;
I would move this to the Player class

2019-10-24 12:02 UTC, Dev-Osmium commented on src/main/java/xyz/devosmium/games/textadventureengine/save/SaveProvider.java
> +                " GOLD           INT     NOT NULL )";
Just making a note to myself that it needs to save inventories as well, though how to do that?

2019-10-24 12:02 UTC, Dev-Osmium commented on src/main/java/xyz/devosmium/games/textadventureengine/save/SaveProvider.java
> +    public void SQLiteSave(Player player) {
Saving looks mostly good, what about loading?

2019-10-24 15:00 UTC, JessieVela commented on src/main/java/xyz/devosmium/games/textadventureengine/save/SaveProvider.java
> +    public void SQLiteSave(Player player) {
Slipped my mind about loading. Will add a loading method.

2019-10-24 15:11 UTC, JessieVela commented on src/main/java/xyz/devosmium/games/textadventureengine/save/SaveProvider.java
> +                " GOLD           INT     NOT NULL )";
I would do the same as stats. Make a table and have a foreign key reference the player.

2019-10-24 15:26 UTC, JessieVela commented on src/main/java/xyz/devosmium/games/textadventureengine/mobiles/Mobile.java
> +    private String playerID;
Done.

2019-10-24 15:47 UTC, Dev-Osmium commented on src/main/java/xyz/devosmium/games/textadventureengine/save/SaveProvider.java
> +                " GOLD           INT     NOT NULL )";
But then how would it scale to different inventory sizes?

2019-10-24 15:55 UTC, JessieVela commented on src/main/java/xyz/devosmium/games/textadventureengine/save/SaveProvider.java
> +                " GOLD           INT     NOT NULL )";
Hmmm well you could insert into the tables the different inventories and update their values as a player gets them.
PlayerID | Potion | Key | Revive | Elixer | Stamina |
123s      |     2      |   0   |     1       |   0     |      4        |

Then you would query the table for items greater than 0. 

If more items get added to the game you would have to go into the code and add them to the table. This is what comes to mind and im sure there are better ways to achieve this.

2019-10-24 16:01 UTC, Dev-Osmium commented on src/main/java/xyz/devosmium/games/textadventureengine/save/SaveProvider.java
> +                " GOLD           INT     NOT NULL )";
Could also have just an inventory table, which had a list of items and a reference back to the player.

2019-10-30 18:51 UTC, JessieVela commented
Quick update: Still working on the Loading portion. Its more complicated than I anticipated.

2019-10-30 20:15 UTC, Dev-Osmium commented
No problem, thanks for the update




---- On Wed, 30 Oct 2019 14:51:54 -0400 JessieVela <mailto:notifications@github.com> wrote ----


Quick update: Still working on the Loading portion. Its more complicated than I anticipated.

—
You are receiving this because your review was requested.
Reply to this email directly, https://github.com/Dev-Osmium/text-adventure-engine/pull/20?email_source=notifications&email_token=ACCMVNU5D5MQZ3WIWMM3EZTQRHJUVA5CNFSM4JEEIDZKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECVMC7Y#issuecomment-548061567, or https://github.com/notifications/unsubscribe-auth/ACCMVNSKPYAIEAZTG3DUBD3QRHJUVANCNFSM4JEEIDZA.

2019-11-04 19:17 UTC, JessieVela commented on src/main/java/xyz/devosmium/games/textadventureengine/save/SaveProvider.java
> +    public void SQLiteSave(Player player) {
Finally got it finished.

2019-11-04 19:18 UTC, JessieVela commented
Finally, finished doing all the changes.

2019-11-06 17:49 UTC, Muirrum requested changes
If you could merge the commit where I fixed the gradle wrapper, that would do it! (commit b2c94a3cf) this should be able to be accomplished by merging develop into the branch.

2019-11-08 22:41 UTC, JessieVela commented
Done.

2019-11-13 13:01 UTC, Muirrum reviewed
Build [fails](https://scans.gradle.com/s/z5hxcxthblol4)

2019-11-16 17:24 UTC, JessieVela commented
Finally have time to take a look. Its failing because of the command interface. This made it into develop. I can fix it and push the changes.
<img width="328" alt="Screen Shot 2019-11-16 at 9 09 48 AM" src="https://user-images.githubusercontent.com/33134794/68996587-ec1dc000-0850-11ea-9039-638646b8a4c6.png">

2019-11-16 17:27 UTC, JessieVela commented
On further review this is going to take a minute to fix. My branch didn't create this and might not have time to solve it but I will try.

2019-11-16 17:32 UTC, JessieVela commented
The whole command engine has issues. It's not even complete.

2020-01-30 00:32 UTC, closed without merging