feat(CommandManager): Class to manage all commands
Dev-Osmium/text-adventure-engine pull request #7
Opened 2019-10-09 03:05 UTC by EikeSan

I change a few things... :D 
The annotation is better using to a class, because the single resposability recommedation, so each class should do only one behaivor.
And with this all Command class should have the CommandAnnotanion and implements the Interface Command. 
If you have any tips or review mention me ;)

2019-10-09 11:24 UTC, Muirrum requested changes
I think in general, beyond my comments, the added CommandManager class and associated classes just need documentation. Once that's added it should be good to merge.

2019-10-09 11:24 UTC, Dev-Osmium commented on pom.xml
> +    </dependency>
These dependencies should be added to build.gradle as well.

2019-10-10 03:39 UTC, EikeSan commented on pom.xml
> +    </dependency>
Added JavaDoc and depencies into gardle

2019-10-10 20:19 UTC, Muirrum approved these changes
Looks good!

2019-10-10 20:19 UTC, Dev-Osmium commented on src/main/java/xyz/devosmium/games/textadventureengine/commands/Attack.java
> + * Class that implements the attack behavior
Minor gripe that shouldn't block this from merging: specify command maybe?

2019-10-10 20:19 UTC, Dev-Osmium commented on src/main/java/xyz/devosmium/games/textadventureengine/commands/Exit.java
> + * Command that shutdown the app (Should implements some save in the future)
Definitely agree with this, should tie in to #5

2019-10-10 20:19 UTC, Dev-Osmium commented on src/main/java/xyz/devosmium/games/textadventureengine/commands/CommandAnnotation.java
> +  String description();
Given the way that the Help command works, I might change this to helpText(), rather than description, but either works.

2019-10-10 23:19 UTC, Dev-Osmium commented
Can you re-create this pull request to the develop branch?

2019-10-10 23:19 UTC, closed without merging

2019-10-10 23:54 UTC, EikeSan commented on src/main/java/xyz/devosmium/games/textadventureengine/commands/Attack.java
> + * Class that implements the attack behavior
It can be like one of yours behaivors guideline 🤣

2019-10-11 00:16 UTC, EikeSan commented on src/main/java/xyz/devosmium/games/textadventureengine/commands/Exit.java
> + * Command that shutdown the app (Should implements some save in the future)
`
{
  "name": "player",
  "level": 1,
  "experience": 0,
  "class": "fighter",
  "health": 100,
  "mana": 100,
  "stats": {
    "agility": 10,
    "intelligence": 10,
    "lucky": 10
  },
  "inventory": [
    {
      "name": "meat",
      "type": "food",
      "quantity": 5,
      "attributes": {
        "healthGain": 15
      }
    },
    {
      "name": "shield",
      "type": "equipment",
      "quantity": 1,
      "attributes": {
        "armor": 5,
        "placeHolder": "hand"
      }
    }
  ],
  "equipment": {
    "head": {
      "name": "helmet",
      "type": "equipment",
      "quantity": 1,
      "attributes": {
        "armor": 5,
        "placeHolder": "head"
      }
    },
    "chest": {
      "name": "armor",
      "type": "equipment",
      "quantity": 1,
      "attributes": {
        "armor": 5,
        "placeHolder": "hand"
      }
    }
  },
  "coordinates": {
    "x": 100000,
    "y": 100000,
    "z": 100000
  }
}
`

You should create models to generate the gson (google json library),  parsing it to file when save and to the model after loading